[project]
include-before = ["vcpkg_config.cmake"]
name = "Outrospection"

[vcpkg]
version = "2021.05.12"
packages = [
    "glad",
    "glfw3",
    "freetype",
]

[find-package]
glad = {}
GLFW3 = {}
FreeType = { }

[target.Outrospection]
type = "executable"
compile-features = ["cxx_std_20"]
sources = [
    "src/**.cpp",
]
include-directories = [
    "src",
    "Libraries/include",
]
link-libraries = [
    "glad::glad",
    "glfw",
    "freetype",
]