[project]
include-before = ["vcpkg_config.cmake"]
name = "Outrospection"

[vcpkg]
version = "2021.05.12"
packages = [
    "glad",
    "glfw3",
    "freetype",
]

[find-package]
glad = {}
glfw3 = {}
FreeType = {}

[conditions]
clang = "CMAKE_CXX_COMPILER_ID MATCHES \"Clang\""
gcc = "CMAKE_CXX_COMPILER_ID STREQUAL \"GNU\""
msvc = "CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\""

[target.Outrospection]
type = "executable"
compile-definitions = ["WITH_MINIAUDIO"]
compile-features = ["cxx_std_20"]
clang.compile-options = ["-Wno-volatile"]
gcc.compile-options = ["-Wno-volatile", "-O2"]
msvc.compile-options = [""]
msvc.link-options = ["/SUBSYSTEM:WINDOWS"]
sources = [
    "src/**.cpp",
    "src/**.c"
]
include-directories = [
    "src",
    "Libraries/include",
]
link-libraries = [
    "glad::glad",
    "glfw",
    "freetype",
]
