name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: microsoft/setup-msbuild@v1
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Build the game!
        run: |
          nuget restore $Env:GITHUB_WORKSPACE/OutrospectionGame.sln
          msbuild $Env:GITHUB_WORKSPACE/OutrospectionGame.sln /property:Configuration=Release /property:Platform=x64
      - name: create-7z-action
        uses: DuckSoft/create-7z-action@v1.0
        with:
          # file/folder path to compress
          pathSource: $Env:GITHUB_WORKSPACE/x64/Release
          # 7z archive path to write
          pathTarget: $Env:GITHUB_WORKSPACE/Outrospection-release.7z
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Latest release built from latest push to master.
          draft: false
          prerelease: true
      - name: Upload Release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing its ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: $Env:GITHUB_WORKSPACE/Outrospection-release.7z
          asset_name: Outrospection-release.7z
          asset_content_type: application/zip
